apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: spring-deploy
  template:
    metadata:
      labels:
        app: spring-deploy
    spec:
      containers:
        - image: hakkou7/kaddem:abdelhak
          name: spring-boot-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8083
#
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: spring-deploy
  type: ClusterIP
--- 
