version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: rayennaffouti/kaddem:rayen
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 9096:9096
    depends_on:
      - mysqldb
