version: "3.3"
services:
  mysqldb:
    container_name: my-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: hakkou7/kaddem:abdelhak
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 9096:8089
    depends_on:
      - mysqldb
